# Generated by Django 5.0.2 on 2024-02-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_modedetransport_reservation_utilisateur_voyage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herbergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=255)),
                ('prixNuit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mdp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
