# Generated by Django 5.0.2 on 2024-02-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_herbergement_utilisateur_ville_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Herbergement',
        ),
    ]
