# Generated by Django 5.0.2 on 2024-02-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_herbergement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herbergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('ville', models.CharField(max_length=255, null=True)),
                ('cp', models.CharField(max_length=255, null=True)),
                ('prixNuit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
