# Generated by Django 5.0.2 on 2024-02-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_herbergement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='herbergement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.herbergement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voyage'),
        ),
    ]
