# Generated by Django 5.0.2 on 2024-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_reservation_herbergement_alter_reservation_voyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbergement',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
